apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart 
  labels:
    app: redis-cart 
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: redis-cart 
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis-cart
        image: redis:alpine
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi  
        ports:
        - containerPort: 6379
