kind: Service
apiVersion: v1
metadata:
  name: loadbalancer-wordpress-svc
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
