apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.31
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mw-configmap
              key: TEST_KEY
        - name: MYSQL_DATABASE
          value: database
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: new-vol
          mountPath: /var/lib/mysql
      volumes:
      - name: new-vol
        awsElasticBlockStore:
          volumeID: "vol-03e455aa34d560b18"
          fsType: ext4
