apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice 
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.7.0
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi  
        env:
          - name: DISABLE_PROFILER
            value: "1"
          - name: PORT
            value: "8080"
        ports:
        - containerPort: 8080
