apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: productcatalogservice 
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.7.0
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi  
        env:
          - name: DISABLE_PROFILER
            value: "1"
          - name: PORT
            value: "3550"
        ports:
        - containerPort: 3550

